# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_xml_sizes <- function(input_file) {
    .Call(`_patentr_get_xml_sizes`, input_file)
}

txt_to_df_cpp <- function(input_file, output_file, append, header) {
    .Call(`_patentr_txt_to_df_cpp`, input_file, output_file, append, header)
}

